import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Sparkles, FileText, Video, Youtube, RefreshCw, ClipboardList, Zap } from 'lucide-react';
import { Card, Button, Input, Badge } from '../components/ui';
import { sessionService } from '../services';
import { useAuth } from '../context';

type Step = 'mode' | 'form' | 'quick-form';

export function CreateSessionPage() {
  const navigate = useNavigate();
  const { user, refreshUser } = useAuth();
  const [step, setStep] = useState<Step>('mode');
  const [selectedMode, setSelectedMode] = useState<string | null>('ai-tutor');
  
  // AI Tutor form state
  const [topic, setTopic] = useState('');
  const [goal, setGoal] = useState('');
  const [totalDays, setTotalDays] = useState(7);
  const [timePerDay, setTimePerDay] = useState('1 hour');
  const [isCreating, setIsCreating] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [error, setError] = useState('');
  const [needsRefresh, setNeedsRefresh] = useState(false);

  // Quick Mode form state
  const [quickTopic, setQuickTopic] = useState('');
  const [quickTarget, setQuickTarget] = useState('');
  const [quickTime, setQuickTime] = useState('1 hour');

  const modes = [
    {
      id: 'ai-tutor',
      icon: Sparkles,
      title: 'AI Tutor',
      description: 'Get a personalized multi-day learning plan generated by AI',
      available: true,
      accent: 'primary',
    },
    {
      id: 'quick-mode',
      icon: Zap,
      title: 'Quick Mode',
      description: 'Learn a topic in one focused session — perfect for small topics, exam prep, or quick revision',
      available: true,
      accent: 'yellow',
    },
    {
      id: 'document-chat',
      icon: FileText,
      title: 'Document Chat',
      description: 'Upload PDFs and chat with your materials',
      available: false,
      accent: 'primary',
    },
    {
      id: 'video-learning',
      icon: Video,
      title: 'Video Learning',
      description: 'Upload videos for interactive learning',
      available: false,
      accent: 'primary',
    },
    {
      id: 'youtube-tutor',
      icon: Youtube,
      title: 'YouTube Tutor',
      description: 'Learn from any YouTube video',
      available: false,
      accent: 'primary',
    },
  ];

  const timeOptions = ['30 min', '1 hour', '2 hours', '3+ hours'];
  const quickTimeOptions = ['15 min', '30 min', '1 hour', '2 hours'];
  const dayOptions = [3, 5, 7, 14, 21, 30];

  const handleRefreshSession = async () => {
    setIsRefreshing(true);
    try {
      await refreshUser();
      setNeedsRefresh(false);
      setError('');
    } catch {
      setError('Failed to refresh session. Please try logging out and back in.');
    } finally {
      setIsRefreshing(false);
    }
  };

  const handleError = (err: unknown) => {
    const errorMsg = err instanceof Error ? err.message : 'Failed to create session';
    if (errorMsg.toLowerCase().includes('email verification') || errorMsg.toLowerCase().includes('verify')) {
      setNeedsRefresh(true);
      setError('Your email has been verified! Click the button below to refresh your session.');
    } else {
      setError(errorMsg);
    }
    setIsCreating(false);
  };

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsCreating(true);

    try {
      const response = await sessionService.create({
        topic,
        total_days: totalDays,
        time_per_day: timePerDay,
        target: goal || undefined,
      });
      navigate(`/sessions/${response.session_id}`);
    } catch (err) {
      handleError(err);
    }
  };

  const handleQuickCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsCreating(true);

    try {
      const response = await sessionService.create({
        topic: quickTopic,
        total_days: 1,
        time_per_day: quickTime,
        mode: 'quick',
        target: quickTarget || 'General understanding',
      });
      // Go directly to chat for quick mode
      navigate(`/chat/${response.session_id}`);
    } catch (err) {
      handleError(err);
    }
  };

  // Error / verification banner component
  const ErrorBanner = () => (
    <>
      {error && (
        <div className="mb-4 p-4 bg-error/10 border border-error/20 rounded-lg">
          <p className="text-error text-sm mb-3">{error}</p>
          {needsRefresh && (
            <Button type="button" variant="outline" size="sm" onClick={handleRefreshSession} isLoading={isRefreshing} className="w-full">
              <RefreshCw className="w-4 h-4 mr-2" />
              Refresh Session
            </Button>
          )}
        </div>
      )}
      {user && !user.is_verified && (
        <div className="mb-4 p-4 bg-warning/10 border border-warning/20 rounded-lg">
          <p className="text-warning text-sm mb-3">
            Please verify your email to create sessions. If you've already verified, click below to refresh.
          </p>
          <Button type="button" variant="outline" size="sm" onClick={handleRefreshSession} isLoading={isRefreshing} className="w-full">
            <RefreshCw className="w-4 h-4 mr-2" />
            Refresh Session
          </Button>
        </div>
      )}
    </>
  );

  // ============ MODE SELECTION ============
  if (step === 'mode') {
    return (
      <div className="max-w-xl mx-auto">
        <Link to="/sessions" className="inline-flex items-center text-gray-400 hover:text-white mb-6 text-sm">
          <ArrowLeft className="w-4 h-4 mr-1" />
          Back to sessions
        </Link>

        <div className="text-center mb-8">
          <h1 className="text-2xl font-bold text-white mb-2">Create Learning Session</h1>
          <p className="text-gray-400">Choose how you want to learn</p>
        </div>

        <div className="space-y-3">
          {modes.map((mode) => (
            <Card
              key={mode.id}
              className={`cursor-pointer transition-all ${
                !mode.available ? 'opacity-50 cursor-not-allowed' : ''
              } ${selectedMode === mode.id ? 'border-primary ring-1 ring-primary' : ''}`}
              padding="md"
              onClick={() => mode.available && setSelectedMode(mode.id)}
            >
              <div className="flex items-center gap-4">
                <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${
                  selectedMode === mode.id 
                    ? 'border-primary bg-primary' 
                    : mode.available
                    ? 'border-gray-500'
                    : 'border-gray-700'
                }`}>
                  {selectedMode === mode.id && (
                    <div className="w-2 h-2 bg-white rounded-full" />
                  )}
                </div>
                
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <mode.icon className={`w-4 h-4 ${
                      mode.id === 'quick-mode' ? 'text-yellow-400' : 
                      mode.available ? 'text-primary' : 'text-gray-500'
                    }`} />
                    <h3 className="font-medium text-white">{mode.title}</h3>
                    {!mode.available && (
                      <Badge variant="gray" size="sm">COMING SOON</Badge>
                    )}
                    {mode.id === 'quick-mode' && (
                      <Badge variant="warning" size="sm">NEW</Badge>
                    )}
                    {mode.available && mode.id === 'ai-tutor' && (
                      <Badge variant="success" size="sm">AVAILABLE</Badge>
                    )}
                  </div>
                  <p className="text-sm text-gray-400 mt-1">{mode.description}</p>
                </div>
              </div>
            </Card>
          ))}
        </div>

        <div className="flex items-center justify-between mt-8">
          <Link to="/sessions" className="text-gray-400 hover:text-white text-sm">
            Cancel
          </Link>
          <Button
            onClick={() => {
              if (selectedMode === 'quick-mode') {
                setStep('quick-form');
              } else {
                setStep('form');
              }
            }}
            disabled={!selectedMode}
          >
            Continue
          </Button>
        </div>
      </div>
    );
  }

  // ============ QUICK MODE FORM ============
  if (step === 'quick-form') {
    return (
      <div className="max-w-lg mx-auto">
        <div className="text-sm text-gray-400 mb-6">
          <Link to="/sessions" className="hover:text-white">Sessions</Link>
          <span className="mx-2">&gt;</span>
          <button onClick={() => setStep('mode')} className="hover:text-white">Create</button>
          <span className="mx-2">&gt;</span>
          <span className="text-yellow-400">Quick Mode</span>
        </div>

        <h1 className="text-2xl font-bold text-white mb-2">⚡ Quick Learning Session</h1>
        <p className="text-gray-400 mb-8">Learn a topic in one focused session</p>

        <ErrorBanner />

        <form onSubmit={handleQuickCreate}>
          <Card padding="lg" className="mb-6">
            <div className="space-y-6">
              <Input
                label="What do you want to learn?"
                placeholder="e.g., Binary Search Trees, CSS Flexbox, Photosynthesis..."
                value={quickTopic}
                onChange={(e) => setQuickTopic(e.target.value)}
                required
              />

              <div>
                <Input
                  label="Target or Goal (optional)"
                  placeholder="e.g., GATE exam, Job interview, Quick revision..."
                  value={quickTarget}
                  onChange={(e) => setQuickTarget(e.target.value)}
                />
                <p className="text-xs text-gray-500 mt-1">
                  Helps the AI focus on what matters most for your goal
                </p>
              </div>

              <div>
                <label className="block text-sm text-gray-400 mb-3">Session Duration</label>
                <div className="flex flex-wrap gap-2">
                  {quickTimeOptions.map((time) => (
                    <button
                      key={time}
                      type="button"
                      onClick={() => setQuickTime(time)}
                      className={`px-4 py-2 rounded-lg text-sm transition-colors ${
                        quickTime === time
                          ? 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30'
                          : 'bg-dark border border-dark-border text-gray-400 hover:text-white'
                      }`}
                    >
                      {time}
                    </button>
                  ))}
                </div>
              </div>

              <div className="h-px bg-dark-border" />

              <div className="bg-dark rounded-lg p-4 flex items-start gap-3">
                <Zap className="w-5 h-5 text-yellow-400 mt-0.5 shrink-0" />
                <p className="text-sm text-gray-400">
                  <span className="text-white font-medium">Quick session: </span>
                  {quickTime} focused learning on "{quickTopic || '...'}"
                  {quickTarget && (
                    <span> targeting <span className="text-yellow-400">{quickTarget}</span></span>
                  )}
                </p>
              </div>
            </div>
          </Card>

          <div className="flex items-center justify-between">
            <button
              type="button"
              onClick={() => setStep('mode')}
              className="text-gray-400 hover:text-white text-sm flex items-center gap-1"
            >
              <ArrowLeft className="w-4 h-4" />
              Back
            </button>
            <Button type="submit" isLoading={isCreating}>
              <Zap className="w-4 h-4 mr-2" />
              Start Learning
            </Button>
          </div>
        </form>
      </div>
    );
  }

  // ============ AI TUTOR FORM ============
  return (
    <div className="max-w-lg mx-auto">
      <div className="text-sm text-gray-400 mb-6">
        <Link to="/sessions" className="hover:text-white">Sessions</Link>
        <span className="mx-2">&gt;</span>
        <button onClick={() => setStep('mode')} className="hover:text-white">Create</button>
        <span className="mx-2">&gt;</span>
        <span className="text-white">AI Tutor</span>
      </div>

      <h1 className="text-2xl font-bold text-white mb-2">Create AI Tutor Session</h1>
      <p className="text-gray-400 mb-8">Our AI will generate a personalized learning plan for you</p>

      <ErrorBanner />

      <form onSubmit={handleCreate}>
        <Card padding="lg" className="mb-6">
          <div className="space-y-6">
            <Input
              label="What do you want to learn?"
              placeholder="e.g., Machine Learning, Spanish, Guitar..."
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              required
            />

            <div>
              <Input
                label="Goal (optional)"
                placeholder="e.g., Crack GATE exam, Build a portfolio project, Career switch..."
                value={goal}
                onChange={(e) => setGoal(e.target.value)}
              />
              <p className="text-xs text-gray-500 mt-1">
                Helps the AI tailor the curriculum to your specific objective
              </p>
            </div>

            <div>
              <label className="block text-sm text-gray-400 mb-2">Duration</label>
              <select
                value={totalDays}
                onChange={(e) => setTotalDays(Number(e.target.value))}
                className="w-full bg-dark border border-dark-border rounded-lg px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-primary"
              >
                {dayOptions.map((days) => (
                  <option key={days} value={days}>{days} days</option>
                ))}
              </select>
              <p className="text-xs text-gray-500 mt-1">How many days for your learning plan</p>
            </div>

            <div>
              <label className="block text-sm text-gray-400 mb-3">Time per day</label>
              <div className="flex flex-wrap gap-2">
                {timeOptions.map((time) => (
                  <button
                    key={time}
                    type="button"
                    onClick={() => setTimePerDay(time)}
                    className={`px-4 py-2 rounded-lg text-sm transition-colors ${
                      timePerDay === time
                        ? 'bg-primary text-white'
                        : 'bg-dark border border-dark-border text-gray-400 hover:text-white'
                    }`}
                  >
                    {time}
                  </button>
                ))}
              </div>
            </div>

            <div className="h-px bg-dark-border" />

            <div className="bg-dark rounded-lg p-4 flex items-start gap-3">
              <ClipboardList className="w-5 h-5 text-primary mt-0.5" />
              <p className="text-sm text-gray-400">
                <span className="text-white font-medium">Your plan: </span>
                {totalDays}-day personalized curriculum with {timePerDay} daily sessions
                {goal && (
                  <span> towards <span className="text-primary">{goal}</span></span>
                )}
              </p>
            </div>
          </div>
        </Card>

        <div className="flex items-center justify-between">
          <button
            type="button"
            onClick={() => setStep('mode')}
            className="text-gray-400 hover:text-white text-sm flex items-center gap-1"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
          <Button type="submit" isLoading={isCreating}>
            Create Plan
          </Button>
        </div>
      </form>
    </div>
  );
}
